var taqHome;
(function(){function xa(){var a=m.getElementById("NewsEditionName"),b=m.getElementById("NewsEditionNumber"),d=m.getElementById("NewsArticleTitle"),c=m.getElementById("NewsArticleAuthor"),g=m.getElementById("NewsArticleID"),f=m.getElementById("NewsArticleType"),B=m.getElementById("NewsPaperName"),w=m.getElementById("NewsArticleSource"),u=m.getElementById("NewsArticlePubDay"),k=m.getElementById("SelfNewsArticleID"),l=m.getElementById("gscrumb"),p=m.getElementById("NewsArticleDepartmentOfAuthor"),n=
m.getElementById("ReserveCustomField");l&&(e.gc=q(l.innerHTML));if(b||g)g&&(e.a_id=q(g.innerHTML)),d&&(d=q(d.innerHTML).replace(/<br.*?>/g," "),e.a_nt=d),b&&(e.a_en=q(b.innerHTML)),a&&(e.a_ea=q(a.innerHTML)),f&&(e.a_tp=q(f.innerHTML)),B&&(e.a_pn=q(B.innerHTML)),w&&(e.a_src=q(w.innerHTML)),c&&(e.a_ar=q(c.innerHTML)),u&&(e.a_pd=q(u.innerHTML)),k&&(e.a_sid=q(k.innerHTML)),p&&(e.a_doa=q(p.innerHTML)),n&&(e.a_rcf=q(n.innerHTML));e.title=x.title||""}function $a(a){M||(s("user state returned."),M=!0,(C=
String(a))&&"null"!=C&&"undefined"!=C?(ca("_trs_user",C,"../../../default.htm",null,R(x.domain)),e.uid=C):(a=R(x.domain),ca("_trs_user","","../../../default.htm",new Date(0),a)))}function ya(a){return null==a||void 0==a?!0:"string"!=typeof a?!1:0==q(a).length}function q(a){return a.replace(/^\s+|\s+$/gm,"")}function n(a,b){return null==a||void 0==a?a:q(a).length>b?a.substring(0,b-3)+"...":a}function da(a){var b=m.cookie.indexOf(a+"=");if(-1==b)return null;b=b+a.length+1;a=m.cookie.indexOf(";",b);-1==a&&(a=m.cookie.length);return decodeURIComponent(m.cookie.substring(b,
a))}function za(a,b,d,c,g){null==g||void 0==g||0==S(g)?m.cookie=a+"="+encodeURIComponent(b)+"; path="+d+"; expires="+c:m.cookie=a+"="+encodeURIComponent(b)+"; path="+d+"; domain="+g+"; expires="+c}function ca(a,b,d,c,g){a=encodeURIComponent(a)+"="+encodeURIComponent(b);d&&(a+="; path="+d);c instanceof Date&&(a+="; expires="+c.toGMTString());g&&(a+="; domain="+g);m.cookie=a}function Aa(a){if(ya(a)||"undefined"==a||"string"!=typeof a)return!0;if(24<a.length)return s("length="+a.length+": "+a),!0;var b=
/^[^_=]{1,5}_\d+_[^_=]{8,9}$/;return/^[^_=]{8,9}_\d+_[^_=]{1,5}$/.test(a)||b.test(a)?!1:(s(a+" not valid"),!0)}function Ba(a){var b=parseInt(Math.floor(1E3*Math.random()+1)+""+Math.floor(1E3*Math.random()+1));return String((new Date).valueOf().toString(36).concat("_").concat(a).concat("_").concat(b.toString(36)))}function s(a){if(window.console&&console.log)try{console.log(a)}catch(b){}}function ab(){var a;try{return a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),a.GetVariable("$version")}catch(b){}try{return a=
new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),version="WIN 6,0,21,0",a.AllowScriptAccess="always",a.GetVariable("$version")}catch(d){}try{return a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3"),a.GetVariable("$version")}catch(c){}try{return new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3"),"WIN 3,0,18,0"}catch(g){}try{return new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),"WIN 2,0,0,11"}catch(f){return"-1"}}function bb(){var a="Shockwave Flash ";if(navigator.plugins&&0<navigator.plugins.length){var b=
navigator.plugins["Shockwave Flash"];if(!b)return"-1";try{if(void 0!=b.version)return b.version}catch(d){}b=b.description;return-1!=b.indexOf(a)?b.substring(a.length):b}for(var b=ab().split(","),c="",a="WIN ",g=0,f=b.length;g<f;g++)-1!=b[g].indexOf(a)?(c+=b[g].substring(a.length),c+="."):g==f-1?c+=b[g]:(c+=b[g],c+=".");return c}function ea(){var a=!e.uid&&!M&&3E3>(new Date).getTime()-Ca;N||("true"!=Da?(xa(),N=!0):S(x.title)?(xa(),N=!0):N=!1);var b=!N&&3E3>(new Date).getTime()-Ea;if(!G)if(1!=fa)G=
!0;else{var d=m.getElementById(Fa);null!=d?""!=q(d.innerHTML)?(e.gc=q(d.innerHTML),G=!0):G=!1:G=!1}d=!G&&3E3>(new Date).getTime()-Ga;if(a||b||d)setTimeout(ea,500);else{var a="",c;for(c in e)ya(e[c])||(""!=a&&(a+="&"),a+=c+"="+encodeURIComponent(e[c]));if(taqHome){try{ga=(new Date).getTime(),Ha=e.mpId}catch(g){}c=new Image(1,1);c.src=taqHome+"/1.gif?"+a;D(c.src,"pv")}else s("no _taq.home!")}}function Ia(a){a=H.timing;try{if(0>=parseInt(a.loadEventEnd))setTimeout(function(){cb++;Ia(e)},50);else{var b=
a.domainLookupEnd-a.domainLookupStart,d=a.connectEnd-a.connectStart,c=a.responseStart-a.requestStart,g=a.domContentLoadedEventStart-a.fetchStart,f=a.responseEnd-a.navigationStart,B=db(),w;-1!==h.navigator.userAgent.indexOf("Chrome")&&(e.p_fp=-1,h.chrome&&window.PerformancePaintTiming&&(w=((performance.getEntriesByType("paint")[0].startTime+performance.timeOrigin)/1E3).toFixed(3),e.p_fp=0<=w?w:-1));-1!=navigator.appName.indexOf("Microsoft Internet Explorer")&&document.all&&(w=a.msFirstPaint-a.navigationStart,
e.p_fp=0<=w?w:-1);requestType=H.navigation.type;var u=a.loadEventEnd-a.navigationStart;e.p_d=0<=b?b:-1;e.p_ct=0<=d?d:-1;e.p_st=0<=c?c:-1;e.p_nt=0<=f?f:-1;e.p_tt=0<=u?u:-1;e.p_dr=0<=g?g:-1;e.p_rt=requestType;e.p_c=0;e.p_tajs=0<=B?Math.floor(B):-1;1===requestType&&(e.p_c=0);0===a.requestStart&&(e.p_c=1);a.connectStart===a.connectEnd&&(e.p_c=1);if("getEntriesByType"in H&&H.getEntriesByType("resource")instanceof Array){var k=H.getEntriesByType("resource");e.p_rc=k.length}ea()}}catch(l){}}function db(){var a=
0;try{var b=m.getElementById("_trs_ta_js").src,d=h.performance.getEntriesByName(b);0<d.length&&(a=d[0].duration)}catch(c){}return a}function eb(a){var b=a.getAttribute("data-trs-ta-event-key");if(null==b||"undefined"==b||""==b||"null"==b){for(;(a=a.parentNode)&&1==a.nodeType;)if(b=a.getAttribute("data-trs-ta-event-key"),null!=b&&"undefined"!=b&&""!=b&&"null"!=b)return a;return null}return a}function S(a){return"string"!=typeof a?!1:0<a.length}function z(a){return null==a||"undefined"==a||""==a||"null"==
a?a:a.replace(/\t/g," ").replace(/(^\s*)|(\s*$)/g,"").replace(/[\r\n]/g," ")}function T(a){return null==a||"undefined"==a||""==a||"null"==a?a:a.replace(/(^\s*)|(\s*$)/g,"")}function k(a,b,d){null!=d&&"undefined"!=d&&""!=d&&"null"!=d&&(a+="&"+b+"="+d);return a}function O(){if("spa"==ha){var a=n(document.URL,1024);return n(encodeURIComponent(a),1024)}return n(encodeURIComponent(P),1024)}function ia(a,b,d){var c=b.getAttribute("href"),g=c?c.match(/^#/):!1,f=g?c:b.href;f&&(f=n(T(f),255));var B=n(b.id,
255),c=n(z(b.innerText),255);d&&d.elemText&&(c=n(z(d.elemText),255));c||(c=ja(b));d=n(b.type,255);var w=n(b.name,255);b=n(b.target,255);a=k(a,"mpId",Ha);a=k(a,"cs",e.cs);a=k(a,"cu",e.cu);a=k(a,"pv",e.pv);a=k(a,"e_id",B);a=k(a,"url",O());if(S(f)&&(a=k(a,"e_tu",encodeURIComponent(f)),!g)){var u,f=T(f);0==f.indexOf("http")||0==f.indexOf("https")?(g=f.substring(0,f.indexOf("://")),f=f.substring(f.indexOf("://")+3),-1<f.indexOf("/")?u=f.substring(0,f.indexOf("/")):u=f):0==f.indexOf("//")?(g=null,f=f.substring(f.indexOf("//")+
2),-1<f.indexOf("/")?u=f.substring(0,f.indexOf("/")):u=f):-1<f.indexOf(":")?(g=f.substring(0,f.indexOf(":")),u=null):(g=null,u=parseDomain2(document.URL));a=k(a,"e_td",encodeURIComponent(u));a=k(a,"e_tp",encodeURIComponent(g))}a=k(a,"e_tt",d);a=k(a,"e_tx",encodeURIComponent(c));a=k(a,"e_en",w);return a=k(a,"e_ht",b)}function D(a,b){if(ka&&la)for(var d=la.split(","),c=!1,g=0;g<d.length;g++){switch(d[g]){case "0":c=!1;break;case "1":c="pv"!=b?!1:!0;break;case "2":c="click"!=b?!1:!0;break;case "3":c=
"track"!=b?!1:!0;break;default:return!1}if(c){a.split("/1.gif?");for(var c=a.split("/1.gif?")[1],f=ka.split(","),e,w=/^(http(s)?:)?\/\//,u,g=0;g<f.length;g++)e=w.test(f[g])?f[g]:"//"+f[g],taqHome!=e&&(u=new Image(1,1),u.src=e+"/1.gif?"+c)}}}function ma(a){var b,d;b=Math.floor(a.pageX);d=Math.floor(a.pageY);var c=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;isNaN(b)&&(d=Math.max(document.documentElement.scrollTop,document.body.scrollTop),b=Math.max(document.documentElement.scrollLeft,
document.body.scrollLeft),d=Math.floor(a.clientY+d),b=Math.floor(a.clientX+b));return{x:b,y:d,z:Math.floor(b-c/2)}}function fb(a){for(var b={flag:!1},d=a;d&&1==d.nodeType;d=d.parentNode)if(d.getAttribute("href")){b.anchorEle=d;b.anchorText=function(){if("area"==d.nodeName.toLowerCase()){var a=d.parentNode,b=a.name||a.id,a=function(){for(var a=null,d=document.getElementsByTagName("img"),c=0;c<d.length;c++)if(d[c].getAttribute("usemap")=="#"+b){a=d[c];break}return a}();return ja(a)}a=n(z(Ja(d)),19);
if(0<a.length)return a;a=n(z(d.title),19);if(0<a.length)return a;var f;return(a=function(){for(var a="",b=d.childNodes,c=0;c<b.length;c++)if(1==b[c].nodeType&&(f||(f=b[c]),"img"==b[c].nodeName.toLowerCase())){a=b[c];break}return a}())?ja(a):f?f.nodeName.toLowerCase()+" "+n(z(Ja(f)),19):""}();b.flag=!0;break}return b}function ja(a){if(!a)return"";var b=a.getAttribute("alt")?T(a.getAttribute("alt")):"",d=a.getAttribute("title")?T(a.getAttribute("title")):"";a=a.getAttribute("src")?a.getAttribute("src"):
"";return n(z(b?b:d?d:a),25)}function Ja(a){return a?"string"==typeof a.textContent?a.textContent:a.innerText:""}function Ka(){if(""!=I){U+="&pa=["+I+"]";I="";var a=new Image(1,1);a.src=U+"&pv="+e.pv;D(a.src,"click","click_1");U=J+"&clicktype=1&url="+O()}}function La(){if(""!=E){v+="&br="+na+"*"+V;v+="&pa=["+E+"]";v+="&pb=["+Q+"]";Q=E="";var a=new Image(1,1);a.src=v;D(a.src,"click","click_3");v=J+"&clicktype=3&url="+O()}}function R(a){for(var b=".com.cn .net.cn .org.cn .gov.cn .edu.cn .ac.cn .mil.cn .ah.cn .bj.cn .cq.cn .fj.cn .gd.cn .gs.cn .gz011BF3F39C".split(" "),
d="",c=0;c<b.length;c++){var d=b[c],g=d.replace(".","\\."),g=new RegExp(g+"$");if(g.test(a)){a=a.replace(g,"");a=a.substring(a.lastIndexOf(".")+1,a.length);a+=d;break}}return a}function F(a,b,d){1<h.ta_count||(a.attachEvent?a.attachEvent("on"+b,d):a.addEventListener&&a.addEventListener(b,d,!1))}function Ma(a){a=document.documentElement&&document.documentElement.scrollHeight||document.body&&document.body.scrollHeight||0;var b=window.innerHeight||V;oa=Math.max(document.documentElement.scrollTop||document.body.scrollTop,
oa);W=Number((oa+b)/a).toFixed(4)}function Na(){}function Oa(a){return a.offsetParent?Oa(a.offsetParent)+a.offsetTop:a.offsetTop}function Pa(a){return a.offsetParent?Pa(a.offsetParent)+a.offsetLeft:a.offsetLeft}function gb(a){var b=[],d=document.getElementById("heatmap");if(d.getContext){var c=d.getContext("2d");d.width=document.body.scrollWidth;d.height=document.body.scrollHeight}else alert("\u6d4f\u89c8\u5668\u4e0d\u652f\u6301canvas!");for(var g in a){var d=a[g].x,f=a[g].y,e=a[g].value,k=a[g].w,
u=a[g].h,l=a[g].scale,m=a[g].ele;if("undefined"!=typeof m){var p=new Na;p.init(d,f,e,k,u,l,m);p.draw(c);b.push(p)}}a=document.getElementById("heatmap");a=a.getContext("2d");var n=document.getElementById("tooltip"),h=[];document.getElementById("heatmap").onmousemove=function(a){var d=a.clientX;a=a.clientY;0==h.length&&(n.style.display="none");for(var c in b)if(0<d-(b[c].x-b[c].w)&&d-(b[c].x-b[c].w)<2*b[c].w&&0<a-(b[c].y-b[c].h)&&a-(b[c].y-b[c].h)<2*b[c].h){if(0<h.length){if(b[c].w>h[0].w||b[c].h>h[0].h)continue;
h.pop().ele.style.border=""}h.push(b[c]);h[0].ele.style.border="2px solid red";h[0].ele.style.boxSizing="border-box";n.style.display="block";n.style.left=d+10+"px";n.style.color="white";n.style.top=a+10+"px";var g="\u70b9\u51fb\u91cf\uff1a"+h[0].value+"<br />\u70b9\u51fb\u7387\uff1a",f;f=h[0].scale;0==f?f=0:(f=Number(100*f).toFixed(5),f+="%");n.innerHTML=g+f}else"undefined"!=typeof b[c].ele&&(b[c].ele.style.border="",b[c]==h[0]&&h.pop())}}var e={},h=window,Qa=function(a,b){var d=a.match(RegExp("(^|&|\\?|#)("+
b+")=([^&#]*)(&|$|#)",""));return d?d[3]:"null"}(h.location.hash.substring(1),"heatShow");h.TA17Obj={};var pa=h.TA17Obj,m=document,Ra=!1,X=function(){var a="",b=document.getElementsByTagName("meta");try{if(0<b.length)for(var d=0;d<b.length;d++){var c=b[d],g=c.getAttribute("charset");if(g){a=g;break}else{var f=c.getAttribute("http-equiv");if(f&&"content-type"==f.toLowerCase()){var e=c.content.split(";"),g=1<e.length?e[1].split("=")[1]:null;if(g){a=g;break}}}}}catch(k){s("fail to parse charset: "+k)}return a.toUpperCase()}(),
qa=(m.characterSet?m.characterSet:m.charset).toUpperCase();e.bc=qa;if(S(X)){e.mc=X;var Sa=/^GB/;if(!(X==qa||Sa.test(X)&&Sa.test(qa))){s("meta charset is different from browser charset, return.");return}}try{Ra=m.domain==top.document.domain}catch(hb){s("unable check top.document.domain: "+hb)}var x=Ra?top.document:m;e.domain=x.domain||"";h&&h.screen&&(e.sh=h.screen.height||0,e.sw=h.screen.width||0,e.cd=h.screen.colorDepth||0);var Ta=m.getElementById("gscrumb");Ta&&(e.gc=q(Ta.innerHTML));var Da=!1,
Ea,N=!1,fa=!1,Fa="",Ga,G=!1,ha=null,K=null,ka=null,la=null;if("undefined"!=typeof _taq){taqHome=_taq.home;for(var r in _taq)switch(_taq[r][0]){case "_mpId":e.mpId=_taq[r][1];break;case "_setUID":_taq[r][1]&&""!=_taq[r][1]&&(e.uid=_taq[r][1])}}else{var ra=m.getElementById("_trs_ta_js");if(!ra){s("not found _trs_ta_js script element, so just return!");return}var Y=ra.src.split("?")[1].split("&");for(r=0;r<Y.length;r++)try{var L=Y[r].split("=")[0],t=Y[r].split("=")[1];"mpid"==L?e.mpId=t:"waitTitle"==
L?Da=t:"waitAjaxElement"==L?""!=q(t)?(Fa=t,fa=!0):fa=!1:"siteType"==L?ha=t:"cPrefix"==L?(K=t,/^(http(s)?:)?\/\//.test(K)||(K="//"+K)):"srcMode"==L&&(4==t&&(t="1,2"),la=t)}catch(kb){s("skip a param as it is not key=value format, i="+r+", myselfSrcParamArray="+Y)}taqHome=K?K:ra.src.split("../../../js/default.htm")[0];ka=document.getElementById("_trs_ta_js").srcsup||document.getElementById("_trs_ta_js").getAttribute("srcsup")||void 0}h.ta_count=h.ta_count||0;if("spa"==ha)h.ta_count++;else{if(h["ta.js"])return;h["ta.js"]=
!0}Ea=(new Date).getTime();Ga=(new Date).getTime();var C=da("_trs_user"),Ca,M=!1;if(C)e.uid=C,s("get user id from cookie");else if("undefined"!=typeof window.TA17Callbacks_getAndSendLoginUser){Ca=(new Date).getTime();try{s("start to get user id"),window.TA17Callbacks_getAndSendLoginUser($a)}catch(lb){s("no valid method for getting user was provided."),M=!0}}else s("no valid method for getting user was provided."),M=!0;pa.clearLoginUser=function(){var a=R(x.domain);ca("_trs_user","","../../../default.htm",new Date(0),
a)};var y,A;e.pv=function(a){var b=parseInt(Math.floor(1E3*Math.random()+1)+""+Math.floor(1E3*Math.random()+1));return String((a+"").concat("_").concat((new Date).valueOf().toString(36)).concat("_").concat(b.toString(36)))}(e.mpId);0<m.cookie.length&&(y=da("_trs_ua_s_1"),A=da("_trs_uv"));if(Aa(y)){var ib=y;y=Ba(e.mpId);s("sessionCookie expired: "+ib+", so create new: "+y)}if(Aa(A)){var jb=A;A=Ba(e.mpId);s("UVCookie expired: "+jb+", so create new: "+A)}var sa=new Date;sa.setDate(sa.getDate()+730);
var Ua=R(x.domain);za("_trs_uv",A,"../../../default.htm",sa.toGMTString(),Ua);s("set UVCookie topLevelDomain: "+Ua+", _trs_uv="+A);var ta=new Date;ta.setMinutes(ta.getMinutes()+30);za("_trs_ua_s_1",y,"../../../default.htm",ta.toGMTString());s("set sessionCookie: _trs_ua_s_1="+y);e.cs=y||"";e.cu=A||"";e.title=x.title||"";e.url=x.URL||"";e.refer=x.referrer||"";if(1==Qa){var Z=document.createElement("iframe"),ua;ua=document.referrer&&"function"==typeof document.referrer.indexOf&&0<=document.referrer.indexOf("/console/heatmap")?document.referrer.slice(0,
document.referrer.indexOf("/console/heatmap")):taqHome;var va=document.documentElement.scrollWidth,$=document.documentElement.scrollHeight,aa=0;Z.src=ua+"/agent.html#"+va+"*"+$;document.body.appendChild(Z);Z.style.display="none";var Va=function(){document.documentElement.scrollHeight!=$?(aa=0,va=document.documentElement.scrollWidth,$=document.documentElement.scrollHeight,Z.src=ua+"/agent.html?random="+Math.random()+"#"+va+"*"+$):3>=aa?(aa++,setTimeout(Va,1E3)):aa=0};F(window,"resize",Va);Qa=0}var ba=
{listenMessage:function(a){F(window,"message",a)},postMessage:function(a){try{window.parent.postMessage(a,"*")}catch(b){s(b.message)}}},Wa=!1;ba.listenMessage(function(a){function b(){document.documentElement.scrollHeight!=c&&(d=document.body.scrollWidth,c=document.documentElement.scrollHeight,ba.postMessage({type:"contentSize",value:[d,c]}))}var d="",c="";a.data&&"taHeatShow"==a.data.type&&(Wa||(Wa=!0,F(window,"resize",b)),d=document.body.scrollWidth,c=document.documentElement.scrollHeight,ba.postMessage({type:"contentSize",
value:[d,c]}))});document.onreadystatechange=function(){window.postMessage&&"complete"==document.readyState&&ba.postMessage({type:"contentSize",value:[document.body.scrollWidth,document.documentElement.scrollHeight]})};navigator&&(e.lang=navigator.language||navigator.browserLanguage||"",e.fl=bb(),e.je=navigator.javaEnabled()?1:0,e.ce=navigator.cookieEnabled?1:0);var H=h.performance,cb=0;H?Ia(e):ea();var ga=0,Ha=e.mpId;/msie (\d+\.\d+)/i.test(navigator.userAgent);var Xa=taqHome+"/1.gif?event=click&sr="+
screen.width+"*"+screen.height+"&url="+encodeURIComponent(document.URL),p=Xa,na=0,V=0;document.all||document.captureEvents(Event.MOUSEMOVE);var na=document.documentElement&&document.documentElement.scrollWidth||document.body&&document.body.scrollWidth||0,V=document.documentElement&&document.documentElement.scrollHeight||document.body&&document.body.scrollHeight||0,wa=window.devicePixelRatio||1,wa=Number(wa).toFixed(4),P=n(document.URL,1024);0<P.indexOf("#")&&(P=P.substring(0,P.indexOf("#")));var J=
taqHome+"/1.gif?event=mousedown&sr="+screen.width+"*"+screen.height+"&br="+na+"*"+V+"&dpr="+wa,U=J+"&clicktype=1&url="+O(),l=J+"&clicktype=2",v=J+"&clicktype=3&url="+O(),I="",E="",Q="";pa.track=function(a){if(!a.eventKey&&0!==a.eventKey)return s("eventKey\u503c\u4e3a\uff1a"+a.eventKey+"\u4e0d\u7b26\u5408\u547d\u540d\u89c4\u8303!"),!1;-1<a.eventKey.indexOf(".")&&(a.eventKey=a.eventKey.substring(a.eventKey.indexOf(".")+1)+"&t_t="+a.eventKey.split(".")[0]);var b,d;if(a.trackInfos&&0!=a.trackInfos.length)for(var c=
0;c<a.trackInfos.length;c++)d=new Image(1,1),b=taqHome+"/1.gif?mpId="+e.mpId+"&event=jsapi&t_k="+a.eventKey+"&cu="+e.cu+"&cs="+e.cs+"&pv="+e.pv+"&url="+encodeURIComponent(e.url),a.trackInfos[c].eventItem&&(b+="&t_i="+a.trackInfos[c].eventItem),a.trackInfos[c].eventItemType&&(b+="&t_it="+a.trackInfos[c].eventItemType),a.trackInfos[c].eventItemName&&(b+="&t_in="+a.trackInfos[c].eventItemName),a.trackInfos[c].commodity_num&&(b+="&t_num="+a.trackInfos[c].commodity_num),a.trackInfos[c].commodity_money&&
(b+="&t_money="+a.trackInfos[c].commodity_money.toFixed(2)),a.trackInfos[c].target_page&&(b+="&e_tu="+a.trackInfos[c].target_page),a.trackInfos[c].customParam&&(b+="&e_cus="+JSON.stringify(a.trackInfos[c].customParam)),d.src=b,D(b,"track");else d=new Image(1,1),b=taqHome+"/1.gif?mpId="+e.mpId+"&event=jsapi&t_k="+a.eventKey+"&cu="+e.cu+"&cs="+e.cs+"&pv="+e.pv+"&url="+e.url,d.src=b,D(b,"track")};if(h.TAQueueArr){for(r=0;r<h.TAQueueArr.length;r++)pa.track(h.TAQueueArr[r][0]);h.TAQueueArr=[]}var Ya=function(){var a=
function(){return{Base64:function(){_keyStr="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";this.encode=function(a){var b="",g,f,e,k,h,l,m=0;for(a=_utf8_encode(a);m<a.length;)g=a.charCodeAt(m++),f=a.charCodeAt(m++),e=a.charCodeAt(m++),k=g>>2,g=(g&3)<<4|f>>4,h=(f&15)<<2|e>>6,l=e&63,isNaN(f)?h=l=64:isNaN(e)&&(l=64),b=b+_keyStr.charAt(k)+_keyStr.charAt(g)+_keyStr.charAt(h)+_keyStr.charAt(l);return b};this.decode=function(a){var b="",g,f,e,k,h,l=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,
"");l<a.length;)g=_keyStr.indexOf(a.charAt(l++)),f=_keyStr.indexOf(a.charAt(l++)),k=_keyStr.indexOf(a.charAt(l++)),h=_keyStr.indexOf(a.charAt(l++)),g=g<<2|f>>4,f=(f&15)<<4|k>>2,e=(k&3)<<6|h,b+=String.fromCharCode(g),64!=k&&(b+=String.fromCharCode(f)),64!=h&&(b+=String.fromCharCode(e));return b=_utf8_decode(b)};_utf8_encode=function(a){a=a.replace(/\r\n/g,"\n");for(var b="",g=0;g<a.length;g++){var f=a.charCodeAt(g);128>f?b+=String.fromCharCode(f):(127<f&&2048>f?b+=String.fromCharCode(f>>6|192):(b+=
String.fromCharCode(f>>12|224),b+=String.fromCharCode(f>>6&63|128)),b+=String.fromCharCode(f&63|128))}return b};_utf8_decode=function(a){for(var b="",g=0,f=c1=c2=0;g<a.length;)f=a.charCodeAt(g),128>f?(b+=String.fromCharCode(f),g++):191<f&&224>f?(c2=a.charCodeAt(g+1),b+=String.fromCharCode((f&31)<<6|c2&63),g+=2):(c2=a.charCodeAt(g+1),c3=a.charCodeAt(g+2),b+=String.fromCharCode((f&15)<<12|(c2&63)<<6|c3&63),g+=3);return b}},readXPath:function(a){if(""!==a.id)return"//*[@id='"+a.id+"']";for(var b=0,g=
a.parentNode,f=a.parentNode.childNodes,e=0,k=f.length;e<k;e++){var l=f[e];if(l==a)return g==document.body?a.tagName.toLowerCase()+(1==b+1?"":"["+(b+1)+"]"):arguments.callee(a.parentNode)+"/"+a.tagName.toLowerCase()+(1==b+1?"":"["+(b+1)+"]");1==l.nodeType&&l.tagName==a.tagName&&b++}},indexOf:function(a,b){if(null!=Array.prototype.indexOf)return a.indexOf(b);for(var g=0;g<a.length;g++)if(a[g]===b)return g;return-1}}}(),b=["TEXTAREA","HTML","BODY"];return{tools:a,collectable:function(d){if(d==document||
!d)return!1;d=d.tagName.toUpperCase();return-1<a.indexOf(b,d)?!1:!0}}}(),Za=Ya.tools;F(document,"mouseup",function(a){if(document!=(a.target||a.srcElement)){var b=eb(a.target||a.srcElement);if(null!=b){var d=b.tagName.toLowerCase();if("a"==d||"input"==d||"button"==d){var c=n(b.getAttribute("data-trs-ta-event-key"),255),g=n(b.getAttribute("data-trs-ta-event-type"),255),f=n(z(b.getAttribute("data-trs-ta-event-itemtype")),255),e=n(z(b.getAttribute("data-trs-ta-event-item")),255),h=n(z(b.getAttribute("data-trs-ta-event-itemname")),
255),m,q,r;r=ma(a);m=r.x;q=r.y;r=r.z;var x=a.type;p=ia(p,b);p=k(p,"t_k",encodeURIComponent(c));p=k(p,"t_t",encodeURIComponent(g));p=k(p,"t_it",encodeURIComponent(f));p=k(p,"t_i",encodeURIComponent(e));p=k(p,"t_in",encodeURIComponent(h));p=k(p,"x",m);p=k(p,"y",q);p=k(p,"x2",r);p=k(p,"e_tn",d);p=k(p,"e_et",x);(new Image(1,1)).src=p;p=Xa}}b=a.target||a.srcElement;if(null!=b&&(f=n(b.tagName.toLowerCase(),255),g=ma(a),d=g.x,c=g.y,g=g.z,e=Ya.collectable(b),h=fb(b),m="a"==f||"input"==f||"button"==f,"a"!=
f&&"input"!=f&&"button"!=f&&(I=""==I?"{"+d+","+c+","+g+"}":I+(";{"+d+","+c+","+g+"}"),Ka()),m||e)){h.flag?(l=ia(l,h.anchorEle,{elemText:h.anchorText}),f=n(h.anchorEle.tagName.toLowerCase(),255),l=k(l,"e_tn",f),l=k(l,"e_iac","1")):(l=ia(l,b),l=k(l,"e_tn",f),l=k(l,"e_iac","0"));f=n(a.type,255);e="";h=0;try{var t=Za.readXPath(b),v=new Za.Base64,e=encodeURIComponent(v.encode(t));0!=ga&&(h=Math.floor(((new Date).getTime()-ga)/1E3))}catch(y){s("someting wrong for getting element xPath"),s(y)}l=k(l,"e_et",
f);l=k(l,"e_nd",e);l=k(l,"e_etd",h);l=k(l,"x",d);l=k(l,"y",c);l=k(l,"x2",g);if(isNaN(d))try{l=k(l,"p_err",JSON.stringify({isPage:a.pageX,isClient:a.clientX,isScroll:document.documentElement.scrollTop,isBodyScroll:document.body.scrollTop}))}catch(A){}t=new Image(1,1);t.src=l;D(t.src,"click","click_2");l=J+"&clicktype=2"}v=ma(a);a=v.x;t=v.y;v=v.z;""==E?(E="{x:"+a+",y:"+t+"}",Q="{z:"+v+",y:"+t+"}"):(E+=",{x:"+a+",y:"+t+"}",Q+=",{z:"+v+",y:"+t+"}");La()}});F(window,"unload",function(){W||Ma();var a=1>
W?W:1,b=new Image(1,1),a=taqHome+"/1.gif?mpId="+e.mpId+"&event=viewInfo&cu="+e.cu+"&cs="+e.cs+"&pv="+e.pv+"&vp="+a+"&url="+encodeURIComponent(e.url);b.src=a;D(a,"leave");Ka();La()});F(window,"scroll",Ma);var oa=0,W;Na.prototype={init:function(a,b,d,c,e,f,h){this.x=a;this.y=b;this.value=d;this.w=c;this.h=e;this.scale=f;this.ele=h},draw:function(a){a.beginPath();a.ellipse(this.x,this.y,this.w,this.h,0,0,2*Math.PI);a.closePath();var b=this.w>this.h?this.w:this.h;0==b&&(b=1);a.save();a.scale(this.w/b,
this.h/b);var d=0==this.h/b?1:this.h/b,c=(this.x/(0==this.w/b?1:this.w/b)).toFixed(2),d=(this.y/d).toFixed(2),b=a.createRadialGradient(c,d,0,c,d,b);.001>this.scale?(b.addColorStop(0,"rgba(0,255,0,0.5)"),b.addColorStop(.5,"rgba(0,0,255,0.3)"),b.addColorStop(1,"rgba(148,0,211,0)")):.008>this.scale?(b.addColorStop(0,"rgba(0,255,255,0.5)"),b.addColorStop(.5,"rgba(0,255,0,0.3)"),b.addColorStop(1,"rgba(0,0,255,0)")):(b.addColorStop(0,"rgba(255,0,0,0.5)"),b.addColorStop(.5,"rgba(255,255,0,0.3)"),b.addColorStop(1,
"rgba(0,255,0,0)"));a.fillStyle=b;a.globalAlpha=Math.max(Math.min(2E3*this.scale,1),0);a.fill();a.restore()}};F(window,"message",function(a){if(a.data&&"dealXpath"==a.data.type){var b=document.createElement("canvas");b.setAttribute("id","heatmap");b.style.position="fixed";b.style.zIndex=999;b.style.display="block";b.style.top=0;b.style.left=0;document.body.appendChild(b);b=document.createElement("div");b.setAttribute("id","tooltip");b.style.backgroundColor="black";b.style.width="150px";b.style.height=
"40px";b.style.padding="10px";b.style.position="fixed";b.style.display="none";b.style.top=0;b.style.left=0;b.style.zIndex=1E3;document.body.appendChild(b);a=a.data.data;for(var b=[],d=0;d<a.length;d++){""==a[d].xpath?a[d].xpath="html/body":0!=a[d].xpath.indexOf("/")&&(a[d].xpath="../../../html/body/"+a[d].xpath);var c=document.evaluate(a[d].xpath,document).iterateNext();if(c&&(0==c.childNodes.length||0!=c.childNodes.length&&0==c.childNodes[0].childNodes.length)){var e=c.offsetWidth/2+Pa(c),f=c.offsetHeight/
2+Oa(c);b.push({x:e,y:f,value:a[d].click,w:c.clientWidth/2,h:c.clientHeight/2,scale:a[d].click/a[d].sumClick,ele:c})}}gb(b)}},!1)})();
